### PR TITLE
Fix compilation errors for libdns v1.0.0

### LINKED ISSUE #1: Not compiling with libdns v1.0.0 due to changes to Record interface
Errors like:

> 149.1 # github.com/libdns/mythicbeasts
149.1 /go/pkg/mod/github.com/libdns/mythicbeasts@v1.0.1/client.go:97:64: record.Type undefined (type libdns.Record has no field or method Type)
149.1 /go/pkg/mod/github.com/libdns/mythicbeasts@v1.0.1/client.go:97:83: record.Name undefined (type libdns.Record has no field or method Name)
149.1 /go/pkg/mod/github.com/libdns/mythicbeasts@v1.0.1/client.go:97:103: record.Value undefined (type libdns.Record has no field or method Value)
149.1 /go/pkg/mod/github.com/libdns/mythicbeasts@v1.0.1/client.go:97:126: record.TTL undefined (type libdns.Record has no field or method TTL)
149.1 /go/pkg/mod/github.com/libdns/mythicbeasts@v1.0.1/client.go:160:64: record.Type undefined (type libdns.Record has no field or method Type)
149.1 /go/pkg/mod/github.com/libdns/mythicbeasts@v1.0.1/client.go:160:83: record.Name undefined (type libdns.Record has no field or method Name)
149.1 /go/pkg/mod/github.com/libdns/mythicbeasts@v1.0.1/client.go:160:103: record.Value undefined (type libdns.Record has no field or method Value)
149.1 /go/pkg/mod/github.com/libdns/mythicbeasts@v1.0.1/client.go:160:126: record.TTL undefined (type libdns.Record has no field or method TTL)
149.1 /go/pkg/mod/github.com/libdns/mythicbeasts@v1.0.1/client.go:174:10: record.Name undefined (type libdns.Record has no field or method Name)
149.1 /go/pkg/mod/github.com/libdns/mythicbeasts@v1.0.1/client.go:175:10: record.Type undefined (type libdns.Record has no field or method Type)
149.1 /go/pkg/mod/github.com/libdns/mythicbeasts@v1.0.1/client.go:175:10: too many errors

According to [libdns/libdns/releases/tag/v1.0.0](https://github.com/libdns/libdns/releases/tag/v1.0.0)
>[Record](https://pkg.go.dev/github.com/libdns/libdns#Record) is now an interface, not a struct type.
[RR](https://pkg.go.dev/github.com/libdns/libdns#RR) is a new struct type that is similar to what Record was, but is a generic representation of a "Resource Record".

This occured during an xcaddy build of caddy. Also see [caddyserver/caddy/releases/tag/v2.10.0](https://github.com/caddyserver/caddy/releases/tag/v2.10.0):
>libdns 1.0 APIs: Many of you use [DNS provider modules](https://github.com/caddy-dns) to solve ACME DNS challenges or to enable dynamic DNS. They implement interfaces defined by [libdns](https://github.com/libdns/libdns) to get, set, append, and delete DNS records. After 5 years of production experience, including lessons learned with ECH, libdns APIs have been updated and 1.0 beta has been tagged. DNS provider packages will need to update their code to be compatible, which will help ensure stability and well-defined semantics for the future. Several packages have already updated or are in the process of updating (cloudflare, rfc2136, and desec to name a few).

I don't have much go experience but I will see if I can make these changes as they appear to be straightforward.

### PR DESCRIPTION
**Pull request by AndrewBoothman**
Currently a first pass at fixing the compilation errors for libdns v1.0.0. See #1

Perhaps not the best fix as our GetRecords() always returns libdns.RR types which looks like is not best practice from the libdns docs: https://pkg.go.dev/github.com/libdns/libdns@v1.0.0#pkg-overview

I've confirmed that it compiles and I can use the code in the _example folder to correctly update a zone hosted at Mythic Beasts.

I'll also see if I can improve GetRecords(), but would appreciate any feedback if anybody is watching.

Fixes #1

### CODE REVIEW

**Comment by AndrewBoothman** [comment]
Actually it looks like I only had to call Parse() on the RR types to get a more specific type, so have done that.

I think this is all that is needed to work with libdns v1.0.0, but I'm going to try with caddy also.

**Comment by AndrewBoothman** [comment]
After I worked out how to include my local copy of the source in an xcaddy build, I'm now using this with caddy v2.10.0 locally and have confirmed that it can still complete an ACME DNS challenge for a new hostname.

Although I've only done simple testing locally - I think this can be merged. @tombish - is this something you can do? And also bump the version referenced in [github.com/caddy-dns/mythicbeasts](https://github.com/caddy-dns/mythicbeasts)?

**Comment by tombish** [comment]
> After I worked out how to include my local copy of the source in an xcaddy build, I'm now using this with caddy v2.10.0 locally and have confirmed that it can still complete an ACME DNS challenge for a new hostname.
> 
> Although I've only done simple testing locally - I think this can be merged. @tombish - is this something you can do? And also bump the version referenced in [github.com/caddy-dns/mythicbeasts](https://github.com/caddy-dns/mythicbeasts)?

Thanks @AndrewBoothman for the issue report and the corresponding bug fix. It all looks fine at first glance,  I will run tests my end first then look to merge.

**Comment by tombish** [comment]
Merged, thank you for pointing out the API incompatibility. Whilst this may have fixed the compilation issue, not all record types are implemented see libdns/mythicbeasts#3. This project certainly could do with some more attention.
